# Generated by Django 4.2.11 on 2024-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.CharField(max_length=100),
        ),
    ]
